from .whoami import *
from .hostname import *
from .pwd import *
from .cd import *
from .ls import *
from .ps import *
from .shell import *
from .powershell import *
from .download import *
from .upload import *
from .sleep import *
from .exit import *